version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/model-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/model-serving"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/monitoring"
    schedule:
      interval: "weekly"
